import type { NextPage } from 'next';
import Head from 'next/head';

// CORE
import { useState } from 'react';

// COMPONENTS
import Navbar from './components/UI/Navbar';
import BasicModal from './components/Modal/BasicModal';

const Home: NextPage = () => {
   const [open, setOpen] = useState(false);

   return (
      <div className="min-h-screen flex flex-col justify-center items-center gap-2">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Navbar />
         <span className="text-2xl font-bold">Naisu</span>

         <button
            onClick={() => setOpen(true)}
            className="px-4 py-2 font-bold rounded-full cursor-pointer border border-indigo-500 transition active:scale-95 hover:text-indigo-500"
         >
            Click Me
         </button>

         <BasicModal open={open} close={() => setOpen(false)}>
            <div className="w-80 md:w-96 h-[1200px] rounded-2xl shadow-sm flex flex-col px-5 bg-white">
               <div className="py-3">
                  <span className="font-bold text-lg">
                     This is some epic shit
                  </span>
               </div>
            </div>
         </BasicModal>
      </div>
   );
};

export default Home;
